/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type ShoppingCart = {
  _id: string;
  _type: "shoppingCart";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clerkUserId?: string;
  items?: Array<{
    product?: ProductReference;
    productName?: string;
    priceAtSave?: number;
    quantity?: number;
    imageUrl?: string;
    slug?: string;
    _key: string;
  }>;
  updatedAt?: string;
};

export type OrderReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "order";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ReturnRequest = {
  _id: string;
  _type: "returnRequest";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  requestNumber?: string;
  order?: OrderReference;
  clerkUserId?: string;
  customerEmail?: string;
  resolution?: "refund" | "exchange" | "repair";
  reason?: "damaged" | "faulty" | "wrong_item" | "not_as_described" | "other";
  notes?: string;
  packagingConfirmed?: boolean;
  evidenceImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  items?: Array<{
    product?: ProductReference;
    productName?: string;
    quantity?: number;
    priceAtPurchase?: number;
    _key: string;
  }>;
  status?: "pending" | "approved" | "received" | "rejected" | "completed";
  adminNotes?: string;
  requestedAt?: string;
  reviewedAt?: string;
  completedAt?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ShippingSettings = {
  _id: string;
  _type: "shippingSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mombasaFee?: number;
  coastalFee?: number;
  nairobiFee?: number;
  otherKenyaFee?: number;
};

export type WishlistItem = {
  _id: string;
  _type: "wishlistItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  product?: ProductReference;
  clerkUserId?: string;
  createdAt?: string;
};

export type RestockSubscription = {
  _id: string;
  _type: "restockSubscription";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  product?: ProductReference;
  clerkUserId?: string;
  email?: string;
  status?: "pending" | "notified" | "cancelled";
  requestedAt?: string;
  notifiedAt?: string;
};

export type Promotion = {
  _id: string;
  _type: "promotion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalTitle?: string;
  status?: "active" | "inactive";
  mediaType?: "image" | "youtube" | "mux";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  youtubeUrl?: string;
  muxVideo?: MuxVideo;
  destinationUrl?: string;
  sortOrder?: number;
  startsAt?: string;
  endsAt?: string;
};

export type MuxVideoAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "mux.videoAsset";
};

export type MuxVideo = {
  _type: "mux.video";
  asset?: MuxVideoAssetReference;
};

export type CustomerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "customer";
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  items?: Array<{
    product?: ProductReference;
    quantity?: number;
    priceAtPurchase?: number;
    _key: string;
  }>;
  total?: number;
  totalPrice?: number;
  subtotal?: number;
  shippingFee?: number;
  products?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  quantities?: Array<number>;
  productPrices?: Array<number>;
  status?: "paid" | "shipped" | "delivered" | "cancelled";
  customer?: CustomerReference;
  clerkUserId?: string;
  email?: string;
  customerEmail?: string;
  address?: {
    name?: string;
    line1?: string;
    line2?: string;
    city?: string;
    postcode?: string;
    country?: string;
  };
  shippingAddress?: {
    name?: string;
    line1?: string;
    line2?: string;
    city?: string;
    postcode?: string;
    county?: string;
    country?: string;
  };
  paystackPaymentId?: string;
  paystackReference?: string;
  inventoryAdjusted?: boolean;
  inventoryIssue?: string;
  createdAt?: string;
  shippedAt?: string;
  deliveredAt?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type BrandReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "brand";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  title?: string;
  slug?: Slug;
  description?: string;
  features?: Array<{
    title?: string;
    description?: string;
    _type: "productFeature";
    _key: string;
  }>;
  price?: number;
  category?: CategoryReference;
  brand?: BrandReference;
  size?: string;
  material?: string;
  color?: string;
  aiKeywords?: Array<string>;
  aiTags?: Array<string>;
  dimensions?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  stock?: number;
  featured?: boolean;
  assemblyRequired?: boolean;
  returnEligibility?: "standard" | "defects_only" | "non_returnable";
  returnWindowDays?: 7 | 14;
  returnPolicyNote?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Customer = {
  _id: string;
  _type: "customer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  name?: string;
  clerkUserId?: string;
  paystackCustomerId?: string;
  shippingAddress?: {
    name?: string;
    line1?: string;
    line2?: string;
    city?: string;
    postcode?: string;
    county?: string;
    country?: string;
  };
  createdAt?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  displayOrder?: number;
  icon?: string;
  parentCategory?: CategoryReference;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type MuxVideoAsset = {
  _id: string;
  _type: "mux.videoAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: string;
  assetId?: string;
  playbackId?: string;
  filename?: string;
  thumbTime?: number;
  data?: MuxAssetData;
};

export type MuxAssetData = {
  _type: "mux.assetData";
  resolution_tier?: string;
  upload_id?: string;
  created_at?: string;
  id?: string;
  status?: string;
  max_stored_resolution?: string;
  passthrough?: string;
  encoding_tier?: string;
  video_quality?: string;
  master_access?: string;
  aspect_ratio?: string;
  duration?: number;
  max_stored_frame_rate?: number;
  mp4_support?: string;
  max_resolution_tier?: string;
  tracks?: Array<
    {
      _key: string;
    } & MuxTrack
  >;
  playback_ids?: Array<
    {
      _key: string;
    } & MuxPlaybackId
  >;
  static_renditions?: MuxStaticRenditions;
  master?: MuxMasterFile;
};

export type MuxMasterFile = {
  _type: "mux.masterFile";
  status?: string;
  url?: string;
};

export type MuxStaticRenditions = {
  _type: "mux.staticRenditions";
  status?: string;
  files?: Array<
    {
      _key: string;
    } & MuxStaticRenditionFile
  >;
};

export type MuxStaticRenditionFile = {
  _type: "mux.staticRenditionFile";
  name?: string;
  ext?: string;
  height?: number;
  width?: number;
  bitrate?: number;
  filesize?: string;
  type?: string;
  status?: string;
  resolution_tier?: string;
  resolution?: string;
  id?: string;
  passthrough?: string;
};

export type MuxPlaybackId = {
  _type: "mux.playbackId";
  id?: string;
  policy?: string;
};

export type MuxTrack = {
  _type: "mux.track";
  id?: string;
  type?: string;
  max_width?: number;
  max_frame_rate?: number;
  duration?: number;
  max_height?: number;
  language_code?: string;
  name?: string;
  status?: string;
  text_source?: string;
  text_type?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProductReference
  | ShoppingCart
  | OrderReference
  | SanityImageAssetReference
  | ReturnRequest
  | SanityImageCrop
  | SanityImageHotspot
  | ShippingSettings
  | WishlistItem
  | RestockSubscription
  | Promotion
  | MuxVideoAssetReference
  | MuxVideo
  | CustomerReference
  | Order
  | CategoryReference
  | BrandReference
  | Product
  | Slug
  | Customer
  | Category
  | Brand
  | MuxVideoAsset
  | MuxAssetData
  | MuxMasterFile
  | MuxStaticRenditions
  | MuxStaticRenditionFile
  | MuxPlaybackId
  | MuxTrack
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/sanity/queries/brands.ts
// Variable: ALL_BRANDS_QUERY
// Query: *[  _type == "brand"] | order(title asc) {  _id,  title,  "slug": slug.current,  logo{    asset->{      _id,      url    }  }}
export type ALL_BRANDS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  logo: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;

// Source: lib/sanity/queries/brands.ts
// Variable: BRANDS_BY_SLUGS_QUERY
// Query: *[  _type == "brand"  && slug.current in $slugs] {  _id,  title,  "slug": slug.current}
export type BRANDS_BY_SLUGS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
}>;

// Source: lib/sanity/queries/cart.ts
// Variable: CART_BY_USER_QUERY
// Query: *[  _type == "shoppingCart"  && clerkUserId == $clerkUserId] | order(updatedAt desc)[0] {  _id,  updatedAt,  items[]{    _key,    quantity,    "productId": product._ref,    "productExists": defined(product->._id),    "name": coalesce(product->title, product->name, productName),    "price": coalesce(product->price, priceAtSave),    "image": coalesce(product->images[0].asset->url, imageUrl),    "slug": coalesce(product->slug.current, slug)  }}
export type CART_BY_USER_QUERY_RESULT = {
  _id: string;
  updatedAt: string | null;
  items: Array<{
    _key: string;
    quantity: number | null;
    productId: string | null;
    productExists: false | true;
    name: string | null;
    price: number | null;
    image: string | null;
    slug: string | null;
  }> | null;
} | null;

// Source: lib/sanity/queries/cart.ts
// Variable: CART_PRODUCTS_QUERY
// Query: *[  _type == "product"  && _id in $productIds] {  _id,  "name": coalesce(title, name),  price,  "image": images[0].asset->url,  "slug": slug.current}
export type CART_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  price: number | null;
  image: string | null;
  slug: string | null;
}>;

// Source: lib/sanity/queries/cart.ts
// Variable: CART_DOCUMENT_BY_USER_QUERY
// Query: *[  _type == "shoppingCart"  && clerkUserId == $clerkUserId] | order(updatedAt desc)[0] {  _id}
export type CART_DOCUMENT_BY_USER_QUERY_RESULT = {
  _id: string;
} | null;

// Source: lib/sanity/queries/categories.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[  _type == "category"] | order(coalesce(displayOrder, 2147483647) asc, title asc) {  _id,  title,  "slug": slug.current,  "parentId": parentCategory._ref,  displayOrder,  "image": image{    asset->{      _id,      url    },    hotspot  }}
export type ALL_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  parentId: string | null;
  displayOrder: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
}>;

// Source: lib/sanity/queries/categories.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[  _type == "category"  && slug.current == $slug][0] {  _id,  title,  "slug": slug.current,  "parentId": parentCategory._ref,  displayOrder,  "image": image{    asset->{      _id,      url    },    hotspot  }}
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  parentId: string | null;
  displayOrder: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
} | null;

// Source: lib/sanity/queries/customers.ts
// Variable: CUSTOMER_ADDRESS_BY_USER_QUERY
// Query: *[  _type == "customer"  && clerkUserId == $clerkUserId] | order(createdAt desc)[0] {  _id,  email,  name,  shippingAddress {    name,    line1,    line2,    city,    postcode,    county,    country  }}
export type CUSTOMER_ADDRESS_BY_USER_QUERY_RESULT = {
  _id: string;
  email: string | null;
  name: string | null;
  shippingAddress: {
    name: string | null;
    line1: string | null;
    line2: string | null;
    city: string | null;
    postcode: string | null;
    county: string | null;
    country: string | null;
  } | null;
} | null;

// Source: lib/sanity/queries/orders.ts
// Variable: ORDERS_BY_USER_QUERY
// Query: *[  _type == "order"  && clerkUserId == $clerkUserId] | order(createdAt desc) {  _id,  orderNumber,  "total": coalesce(totalPrice, total),  status,  createdAt,  "itemCount": select(defined(products) => count(products), count(items)),  "itemNames": select(    defined(products) => products[]->{"value": coalesce(title, name)}.value,    coalesce(items[].product->title, items[].product->name)  ),  "itemImages": select(    defined(products) => products[]->images[0].asset->url,    items[].product->images[0].asset->url  )}
export type ORDERS_BY_USER_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: string | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  createdAt: string | null;
  itemCount: number | null;
  itemNames: Array<string | null> | null;
  itemImages: Array<string | null> | null;
}>;

// Source: lib/sanity/queries/orders.ts
// Variable: ORDER_BY_ID_QUERY
// Query: *[  _type == "order"  && _id == $id][0] {  _id,  orderNumber,  clerkUserId,  "email": coalesce(customerEmail, email),  products[]->{    _id,    "name": coalesce(title, name),    "slug": slug.current,    "image": images[0]{      asset->{        _id,        url      }    }  },  quantities,  productPrices,  subtotal,  shippingFee,  "legacyItems": items[]{    _key,    quantity,    priceAtPurchase,    product->{      _id,      "name": coalesce(title, name),      "slug": slug.current,      "image": images[0]{        asset->{          _id,          url        }      }    }  },  "total": coalesce(totalPrice, total),  status,  "address": coalesce(shippingAddress, address),  paystackReference,  createdAt}
export type ORDER_BY_ID_QUERY_RESULT = {
  _id: string;
  orderNumber: string | null;
  clerkUserId: string | null;
  email: string | null;
  products: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    image: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
    } | null;
  }> | null;
  quantities: Array<number> | null;
  productPrices: Array<number> | null;
  subtotal: number | null;
  shippingFee: number | null;
  legacyItems: Array<{
    _key: string;
    quantity: number | null;
    priceAtPurchase: number | null;
    product: {
      _id: string;
      name: string | null;
      slug: string | null;
      image: {
        asset: {
          _id: string;
          url: string | null;
        } | null;
      } | null;
    } | null;
  }> | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  address:
    | {
        name?: string;
        line1?: string;
        line2?: string;
        city?: string;
        postcode?: string;
        county?: string;
        country?: string;
      }
    | {
        name?: string;
        line1?: string;
        line2?: string;
        city?: string;
        postcode?: string;
        country?: string;
      }
    | null;
  paystackReference: string | null;
  createdAt: string | null;
} | null;

// Source: lib/sanity/queries/orders.ts
// Variable: RECENT_ORDERS_QUERY
// Query: *[  _type == "order"] | order(createdAt desc) [0...$limit] {  _id,  orderNumber,  "email": coalesce(customerEmail, email),  "total": coalesce(totalPrice, total),  status,  createdAt}
export type RECENT_ORDERS_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: string | null;
  email: string | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  createdAt: string | null;
}>;

// Source: lib/sanity/queries/orders.ts
// Variable: ORDER_BY_PAYSTACK_REFERENCE_QUERY
// Query: *[  _type == "order"  && paystackReference == $paystackReference][0]{ _id }
export type ORDER_BY_PAYSTACK_REFERENCE_QUERY_RESULT = {
  _id: string;
} | null;

// Source: lib/sanity/queries/orders.ts
// Variable: ORDER_STATUS_BY_PAYSTACK_REFERENCE_QUERY
// Query: *[  _type == "order"  && paystackReference == $paystackReference][0]{  _id,  clerkUserId,  status}
export type ORDER_STATUS_BY_PAYSTACK_REFERENCE_QUERY_RESULT = {
  _id: string;
  clerkUserId: string | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
} | null;

// Source: lib/sanity/queries/products.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: *[  _type == "product"] | order(coalesce(title, name) asc) {  _id,  "name": coalesce(title, name),  "slug": slug.current,  description,  price,  "images": images[]{    _key,    asset->{      _id,      url    },    hotspot  },  category->{    _id,    title,    "slug": slug.current  },  dimensions,  stock,  featured,  assemblyRequired}
export type ALL_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  dimensions: string | null;
  stock: number | null;
  featured: boolean | null;
  assemblyRequired: boolean | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: FEATURED_PRODUCTS_QUERY
// Query: *[  _type == "product"  && stock > 0  && featured == true] | order(coalesce(title, name) asc) [0...6] {  _id,  "name": coalesce(title, name),  "slug": slug.current,  description,  price,  "images": images[]{    _key,    asset->{      _id,      url    },    hotspot  },  category->{    _id,    title,    "slug": slug.current  },  brand->{    _id,    title,    "slug": slug.current  },  stock}
export type FEATURED_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  brand: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: PRODUCTS_BY_CATEGORY_QUERY
// Query: *[  _type == "product"  && category->slug.current == $categorySlug] | order(coalesce(title, name) asc) {  _id,  "name": coalesce(title, name),  "slug": slug.current,  price,  "image": images[0]{    asset->{      _id,      url    },    hotspot  },  category->{    _id,    title,    "slug": slug.current  },  stock}
export type PRODUCTS_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[  _type == "product"  && (slug.current == $identifier || _id == $identifier)][0] {  _id,  "name": coalesce(title, name),  "slug": slug.current,  description,  features[]{_key, title, description},  price,  "images": images[]{    _key,    asset->{      _id,      url    },    hotspot  },  category->{    _id,    title,    "slug": slug.current  },  brand->{    _id,    title,    "slug": slug.current  },  color,  size,  dimensions,  stock,  featured,  assemblyRequired}
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  features: Array<{
    _key: string;
    title: string | null;
    description: string | null;
  }> | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  brand: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  color: string | null;
  size: string | null;
  dimensions: string | null;
  stock: number | null;
  featured: boolean | null;
  assemblyRequired: boolean | null;
} | null;

// Source: lib/sanity/queries/products.ts
// Variable: SEARCH_PRODUCTS_QUERY
// Query: *[  _type == "product"  && (    coalesce(title, name) match $searchQuery + "*"    || description match $searchQuery + "*"    || aiKeywords[] match $searchQuery + "*"    || aiTags[] match $searchQuery + "*"  )] | score(  boost(coalesce(title, name) match $searchQuery + "*", 3),  boost(aiKeywords[] match $searchQuery + "*", 2),  boost(aiTags[] match $searchQuery + "*", 2),  boost(description match $searchQuery + "*", 1)) | order(_score desc) {  _id,  _score,  "name": coalesce(title, name),  "slug": slug.current,  price,  "image": images[0]{    asset->{      _id,      url    },    hotspot  },  category->{    _id,    title,    "slug": slug.current  },  stock}
export type SEARCH_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  _score: null;
  name: string | null;
  slug: string | null;
  price: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: FILTER_PRODUCTS_BY_NAME_QUERY
// Query: *[  _type == "product"  && (count($categoryIds) == 0 || category._ref in $categoryIds)  && (count($brandIds) == 0 || brand._ref in $brandIds)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")  && ($inStock == false || stock > 0)] | order(coalesce(title, name) asc) {  _id,  "name": coalesce(title, name),  "slug": slug.current,  price,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  brand->{    _id,    title,    "slug": slug.current  },  stock}
export type FILTER_PRODUCTS_BY_NAME_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  brand: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: FILTER_PRODUCTS_BY_PRICE_ASC_QUERY
// Query: *[  _type == "product"  && (count($categoryIds) == 0 || category._ref in $categoryIds)  && (count($brandIds) == 0 || brand._ref in $brandIds)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")  && ($inStock == false || stock > 0)] | order(price asc) {  _id,  "name": coalesce(title, name),  "slug": slug.current,  price,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  brand->{    _id,    title,    "slug": slug.current  },  stock}
export type FILTER_PRODUCTS_BY_PRICE_ASC_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  brand: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: FILTER_PRODUCTS_BY_PRICE_DESC_QUERY
// Query: *[  _type == "product"  && (count($categoryIds) == 0 || category._ref in $categoryIds)  && (count($brandIds) == 0 || brand._ref in $brandIds)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")  && ($inStock == false || stock > 0)] | order(price desc) {  _id,  "name": coalesce(title, name),  "slug": slug.current,  price,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  brand->{    _id,    title,    "slug": slug.current  },  stock}
export type FILTER_PRODUCTS_BY_PRICE_DESC_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  brand: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: FILTER_PRODUCTS_BY_RELEVANCE_QUERY
// Query: *[  _type == "product"  && (count($categoryIds) == 0 || category._ref in $categoryIds)  && (count($brandIds) == 0 || brand._ref in $brandIds)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")  && ($inStock == false || stock > 0)] | score(  boost(coalesce(title, name) match $searchQuery + "*", 3),  boost(aiKeywords[] match $searchQuery + "*", 2),  boost(aiTags[] match $searchQuery + "*", 2),  boost(features[].title match $searchQuery + "*", 2),  boost(features[].description match $searchQuery + "*", 1),  boost(description match $searchQuery + "*", 1)) | order(_score desc, coalesce(title, name) asc) {  _id,  "name": coalesce(title, name),  "slug": slug.current,  price,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  brand->{    _id,    title,    "slug": slug.current  },  stock}
export type FILTER_PRODUCTS_BY_RELEVANCE_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  brand: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: PRODUCT_PRICE_FACET_QUERY
// Query: *[    _type == "product"  && (count($categoryIds) == 0 || category._ref in $categoryIds)  && (count($brandIds) == 0 || brand._ref in $brandIds)  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")  && ($inStock == false || stock > 0)  && defined(price)].price
export type PRODUCT_PRICE_FACET_QUERY_RESULT = Array<number | null>;

// Source: lib/sanity/queries/products.ts
// Variable: PRODUCTS_BY_IDS_QUERY
// Query: *[  _type == "product"  && _id in $ids] {  _id,  "name": coalesce(title, name),  "slug": slug.current,  price,  "image": images[0]{    asset->{      _id,      url    },    hotspot  },  stock}
export type PRODUCTS_BY_IDS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  stock: number | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: LOW_STOCK_PRODUCTS_QUERY
// Query: *[  _type == "product"  && stock > 0  && stock <= 5] | order(stock asc) {  _id,  "name": coalesce(title, name),  "slug": slug.current,  stock,  "image": images[0]{    asset->{      _id,      url    }  }}
export type LOW_STOCK_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  stock: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: OUT_OF_STOCK_PRODUCTS_QUERY
// Query: *[  _type == "product"  && stock == 0] | order(coalesce(title, name) asc) {  _id,  "name": coalesce(title, name),  "slug": slug.current,  "image": images[0]{    asset->{      _id,      url    }  }}
export type OUT_OF_STOCK_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: AI_SEARCH_PRODUCTS_QUERY
// Query: *[    _type == "product"  && (count($categoryIds) == 0 || category._ref in $categoryIds)  && (count($brandIds) == 0 || brand._ref in $brandIds)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")  && ($inStock == false || stock > 0)] | score(  boost(coalesce(title, name) match $searchQuery + "*", 3),  boost(aiKeywords[] match $searchQuery + "*", 2),  boost(aiTags[] match $searchQuery + "*", 2),  boost(features[].title match $searchQuery + "*", 2),  boost(features[].description match $searchQuery + "*", 1),  boost(description match $searchQuery + "*", 1)) | order(_score desc, coalesce(title, name) asc) [0...20] {  _id,  "name": coalesce(title, name),  "slug": slug.current,  description,  features[]{_key, title, description},  price,  "image": images[0]{    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  brand->{    _id,    title,    "slug": slug.current  },  color,  size,  dimensions,  stock,  featured,  assemblyRequired}
export type AI_SEARCH_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  features: Array<{
    _key: string;
    title: string | null;
    description: string | null;
  }> | null;
  price: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  brand: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  color: string | null;
  size: string | null;
  dimensions: string | null;
  stock: number | null;
  featured: boolean | null;
  assemblyRequired: boolean | null;
}>;

// Source: lib/sanity/queries/promotions.ts
// Variable: ACTIVE_PROMOTIONS_QUERY
// Query: *[  _type == "promotion"  && status == "active"  && (!defined(startsAt) || dateTime(startsAt) <= dateTime(now()))  && (!defined(endsAt) || dateTime(endsAt) >= dateTime(now()))] | order(sortOrder asc, _createdAt desc) [0...6] {  _id,  internalTitle,  mediaType,  image {    asset->{      _id,      url,      metadata {        lqip,        dimensions { width, height }      }    },    alt,    hotspot,    crop  },  youtubeUrl,  muxVideo {    asset->{      playbackId,      status,      filename,      data {        aspect_ratio,        duration      }    }  },  destinationUrl}
export type ACTIVE_PROMOTIONS_QUERY_RESULT = Array<{
  _id: string;
  internalTitle: string | null;
  mediaType: "image" | "mux" | "youtube" | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  youtubeUrl: string | null;
  muxVideo: {
    asset: {
      playbackId: string | null;
      status: string | null;
      filename: string | null;
      data: {
        aspect_ratio: string | null;
        duration: number | null;
      } | null;
    } | null;
  } | null;
  destinationUrl: string | null;
}>;

// Source: lib/sanity/queries/restock-subscriptions.ts
// Variable: RESTOCK_PRODUCT_QUERY
// Query: *[  _type == "product" && _id == $productId][0] {  _id,  "name": coalesce(title, name),  "slug": slug.current,  stock}
export type RESTOCK_PRODUCT_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  stock: number | null;
} | null;

// Source: lib/sanity/queries/restock-subscriptions.ts
// Variable: ACTIVE_RESTOCK_SUBSCRIPTION_QUERY
// Query: *[  _type == "restockSubscription"  && clerkUserId == $clerkUserId  && product._ref == $productId  && status == "pending"] | order(requestedAt desc)[0] {  _id,  status,  requestedAt}
export type ACTIVE_RESTOCK_SUBSCRIPTION_QUERY_RESULT = {
  _id: string;
  status: "cancelled" | "notified" | "pending" | null;
  requestedAt: string | null;
} | null;

// Source: lib/sanity/queries/returns.ts
// Variable: DELIVERED_ORDERS_FOR_RETURNS_QUERY
// Query: *[  _type == "order"  && clerkUserId == $clerkUserId  && status == "delivered"] | order(createdAt desc) {  _id,  orderNumber,  createdAt,  deliveredAt,  "deliveryDate": coalesce(deliveredAt, _updatedAt, createdAt),  products[]->{    _id,    "name": coalesce(title, name),    "returnEligibility": coalesce(returnEligibility, "standard"),    "returnWindowDays": coalesce(returnWindowDays, 14),    returnPolicyNote  },  quantities,  productPrices,  "legacyItems": items[]{    _key,    quantity,    priceAtPurchase,    product->{      _id,      "name": coalesce(title, name),      "returnEligibility": coalesce(returnEligibility, "standard"),      "returnWindowDays": coalesce(returnWindowDays, 14),      returnPolicyNote    }  }}
export type DELIVERED_ORDERS_FOR_RETURNS_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: string | null;
  createdAt: string | null;
  deliveredAt: string | null;
  deliveryDate: string;
  products: Array<{
    _id: string;
    name: string | null;
    returnEligibility: "defects_only" | "non_returnable" | "standard";
    returnWindowDays: 14 | 7;
    returnPolicyNote: string | null;
  }> | null;
  quantities: Array<number> | null;
  productPrices: Array<number> | null;
  legacyItems: Array<{
    _key: string;
    quantity: number | null;
    priceAtPurchase: number | null;
    product: {
      _id: string;
      name: string | null;
      returnEligibility: "defects_only" | "non_returnable" | "standard";
      returnWindowDays: 14 | 7;
      returnPolicyNote: string | null;
    } | null;
  }> | null;
}>;

// Source: lib/sanity/queries/returns.ts
// Variable: RETURN_ORDER_BY_ID_QUERY
// Query: *[  _type == "order"  && _id == $orderId][0] {  _id,  orderNumber,  clerkUserId,  "email": coalesce(customerEmail, email),  status,  deliveredAt,  createdAt,  "deliveryDate": coalesce(deliveredAt, _updatedAt, createdAt),  products[]->{    _id,    "name": coalesce(title, name),    "returnEligibility": coalesce(returnEligibility, "standard"),    "returnWindowDays": coalesce(returnWindowDays, 14),    returnPolicyNote  },  quantities,  productPrices,  "legacyItems": items[]{    _key,    quantity,    priceAtPurchase,    product->{      _id,      "name": coalesce(title, name),      "returnEligibility": coalesce(returnEligibility, "standard"),      "returnWindowDays": coalesce(returnWindowDays, 14),      returnPolicyNote    }  }}
export type RETURN_ORDER_BY_ID_QUERY_RESULT = {
  _id: string;
  orderNumber: string | null;
  clerkUserId: string | null;
  email: string | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  deliveredAt: string | null;
  createdAt: string | null;
  deliveryDate: string;
  products: Array<{
    _id: string;
    name: string | null;
    returnEligibility: "defects_only" | "non_returnable" | "standard";
    returnWindowDays: 14 | 7;
    returnPolicyNote: string | null;
  }> | null;
  quantities: Array<number> | null;
  productPrices: Array<number> | null;
  legacyItems: Array<{
    _key: string;
    quantity: number | null;
    priceAtPurchase: number | null;
    product: {
      _id: string;
      name: string | null;
      returnEligibility: "defects_only" | "non_returnable" | "standard";
      returnWindowDays: 14 | 7;
      returnPolicyNote: string | null;
    } | null;
  }> | null;
} | null;

// Source: lib/sanity/queries/returns.ts
// Variable: ACTIVE_RETURN_ITEMS_BY_ORDER_QUERY
// Query: *[  _type == "returnRequest"  && order._ref == $orderId  && status in ["pending", "approved", "received", "completed"]] {  items[]{    quantity,    "productId": product._ref  }}
export type ACTIVE_RETURN_ITEMS_BY_ORDER_QUERY_RESULT = Array<{
  items: Array<{
    quantity: number | null;
    productId: string | null;
  }> | null;
}>;

// Source: lib/sanity/queries/returns.ts
// Variable: RETURNS_BY_USER_QUERY
// Query: *[  _type == "returnRequest"  && clerkUserId == $clerkUserId] | order(requestedAt desc) {  _id,  requestNumber,  "orderId": order._ref,  "orderNumber": order->orderNumber,  resolution,  reason,  notes,  status,  adminNotes,  requestedAt,  reviewedAt,  completedAt,  "evidenceImageUrls": evidenceImages[].asset->url,  items[]{    _key,    quantity,    productName,    priceAtPurchase,    "productId": product._ref  }}
export type RETURNS_BY_USER_QUERY_RESULT = Array<{
  _id: string;
  requestNumber: string | null;
  orderId: string | null;
  orderNumber: string | null;
  resolution: "exchange" | "refund" | "repair" | null;
  reason:
    "damaged" | "faulty" | "not_as_described" | "other" | "wrong_item" | null;
  notes: string | null;
  status: "approved" | "completed" | "pending" | "received" | "rejected" | null;
  adminNotes: string | null;
  requestedAt: string | null;
  reviewedAt: string | null;
  completedAt: string | null;
  evidenceImageUrls: Array<string | null> | null;
  items: Array<{
    _key: string;
    quantity: number | null;
    productName: string | null;
    priceAtPurchase: number | null;
    productId: string | null;
  }> | null;
}>;

// Source: lib/sanity/queries/shipping.ts
// Variable: SHIPPING_SETTINGS_QUERY
// Query: *[  _type == "shippingSettings" && _id == "shippingSettings"][0] {  mombasaFee,  coastalFee,  nairobiFee,  otherKenyaFee}
export type SHIPPING_SETTINGS_QUERY_RESULT = {
  mombasaFee: number | null;
  coastalFee: number | null;
  nairobiFee: number | null;
  otherKenyaFee: number | null;
} | null;

// Source: lib/sanity/queries/stats.ts
// Variable: ORDERS_LAST_7_DAYS_QUERY
// Query: *[  _type == "order"  && createdAt >= $startDate  && !(_id in path("drafts.**"))] | order(createdAt desc) {  _id,  orderNumber,  "total": coalesce(totalPrice, total),  status,  createdAt,  "itemCount": select(defined(products) => count(products), count(items)),  products[]->{    "productName": coalesce(title, name),    "productId": _id,    price  },  quantities,  productPrices,  "legacyItems": items[]{    quantity,    priceAtPurchase,    "productName": coalesce(product->title, product->name),    "productId": product->_id  }}
export type ORDERS_LAST_7_DAYS_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: string | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  createdAt: string | null;
  itemCount: number | null;
  products: Array<{
    productName: string | null;
    productId: string;
    price: number | null;
  }> | null;
  quantities: Array<number> | null;
  productPrices: Array<number> | null;
  legacyItems: Array<{
    quantity: number | null;
    priceAtPurchase: number | null;
    productName: string | null;
    productId: string | null;
  }> | null;
}>;

// Source: lib/sanity/queries/stats.ts
// Variable: ORDER_STATUS_DISTRIBUTION_QUERY
// Query: {  "paid": count(*[_type == "order" && status == "paid" && !(_id in path("drafts.**"))]),  "shipped": count(*[_type == "order" && status == "shipped" && !(_id in path("drafts.**"))]),  "delivered": count(*[_type == "order" && status == "delivered" && !(_id in path("drafts.**"))]),  "cancelled": count(*[_type == "order" && status == "cancelled" && !(_id in path("drafts.**"))])}
export type ORDER_STATUS_DISTRIBUTION_QUERY_RESULT = {
  paid: number;
  shipped: number;
  delivered: number;
  cancelled: number;
};

// Source: lib/sanity/queries/stats.ts
// Variable: TOP_SELLING_PRODUCTS_QUERY
// Query: *[  _type == "order"  && status in ["paid", "shipped", "delivered"]  && !(_id in path("drafts.**"))] {  products[]->{    "productId": _id,    "productName": coalesce(title, name),    "productPrice": price  },  quantities,  productPrices,  "legacyItems": items[]{    "productId": product->_id,    "productName": coalesce(product->title, product->name),    "productPrice": product->price,    quantity  }}
export type TOP_SELLING_PRODUCTS_QUERY_RESULT = Array<{
  products: Array<{
    productId: string;
    productName: string | null;
    productPrice: number | null;
  }> | null;
  quantities: Array<number> | null;
  productPrices: Array<number> | null;
  legacyItems: Array<{
    productId: string | null;
    productName: string | null;
    productPrice: number | null;
    quantity: number | null;
  }> | null;
}>;

// Source: lib/sanity/queries/stats.ts
// Variable: PRODUCTS_INVENTORY_QUERY
// Query: *[_type == "product"] {  _id,  "name": coalesce(title, name),  price,  stock,  "category": category->title}
export type PRODUCTS_INVENTORY_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  price: number | null;
  stock: number | null;
  category: string | null;
}>;

// Source: lib/sanity/queries/stats.ts
// Variable: UNFULFILLED_ORDERS_QUERY
// Query: *[  _type == "order"  && status == "paid"  && !(_id in path("drafts.**"))] | order(createdAt asc) {  _id,  orderNumber,  "total": coalesce(totalPrice, total),  createdAt,  "email": coalesce(customerEmail, email),  "itemCount": select(defined(products) => count(products), count(items))}
export type UNFULFILLED_ORDERS_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: string | null;
  total: number | null;
  createdAt: string | null;
  email: string | null;
  itemCount: number | null;
}>;

// Source: lib/sanity/queries/stats.ts
// Variable: REVENUE_BY_PERIOD_QUERY
// Query: {  "currentPeriod": math::sum(*[    _type == "order"    && status in ["paid", "shipped", "delivered"]    && createdAt >= $currentStart    && !(_id in path("drafts.**"))  ]{"value": coalesce(totalPrice, total)}.value),  "previousPeriod": math::sum(*[    _type == "order"    && status in ["paid", "shipped", "delivered"]    && createdAt >= $previousStart    && createdAt < $currentStart    && !(_id in path("drafts.**"))  ]{"value": coalesce(totalPrice, total)}.value),  "currentOrderCount": count(*[    _type == "order"    && createdAt >= $currentStart    && !(_id in path("drafts.**"))  ]),  "previousOrderCount": count(*[    _type == "order"    && createdAt >= $previousStart    && createdAt < $currentStart    && !(_id in path("drafts.**"))  ])}
export type REVENUE_BY_PERIOD_QUERY_RESULT = {
  currentPeriod: number;
  previousPeriod: number;
  currentOrderCount: number;
  previousOrderCount: number;
};

// Source: lib/sanity/queries/wishlist.ts
// Variable: WISHLIST_PRODUCT_QUERY
// Query: *[  _type == "product" && _id == $productId][0] {  _id,  "name": coalesce(title, name)}
export type WISHLIST_PRODUCT_QUERY_RESULT = {
  _id: string;
  name: string | null;
} | null;

// Source: lib/sanity/queries/wishlist.ts
// Variable: WISHLIST_ITEM_QUERY
// Query: *[  _type == "wishlistItem"  && clerkUserId == $clerkUserId  && product._ref == $productId] | order(createdAt desc)[0] {  _id,  createdAt}
export type WISHLIST_ITEM_QUERY_RESULT = {
  _id: string;
  createdAt: string | null;
} | null;

// Source: lib/sanity/queries/wishlist.ts
// Variable: WISHLIST_COUNT_QUERY
// Query: count(*[  _type == "wishlistItem"  && clerkUserId == $clerkUserId  && defined(product->._id)])
export type WISHLIST_COUNT_QUERY_RESULT = number;

// Source: lib/sanity/queries/wishlist.ts
// Variable: WISHLIST_BY_USER_QUERY
// Query: *[  _type == "wishlistItem"  && clerkUserId == $clerkUserId  && defined(product->._id)] | order(createdAt desc) {  _id,  createdAt,  product->{    _id,    "name": coalesce(title, name),    "slug": slug.current,    price,    "images": images[0...4]{      _key,      asset->{        _id,        url      }    },    category->{      _id,      title,      "slug": slug.current    },    brand->{      _id,      title,      "slug": slug.current    },    stock  }}
export type WISHLIST_BY_USER_QUERY_RESULT = Array<{
  _id: string;
  createdAt: string | null;
  product: {
    _id: string;
    name: string | null;
    slug: string | null;
    price: number | null;
    images: Array<{
      _key: string;
      asset: {
        _id: string;
        url: string | null;
      } | null;
    }> | null;
    category: {
      _id: string;
      title: string | null;
      slug: string | null;
    } | null;
    brand: {
      _id: string;
      title: string | null;
      slug: string | null;
    } | null;
    stock: number | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[\n  _type == "brand"\n] | order(title asc) {\n  _id,\n  title,\n  "slug": slug.current,\n  logo{\n    asset->{\n      _id,\n      url\n    }\n  }\n}': ALL_BRANDS_QUERY_RESULT;
    '*[\n  _type == "brand"\n  && slug.current in $slugs\n] {\n  _id,\n  title,\n  "slug": slug.current\n}': BRANDS_BY_SLUGS_QUERY_RESULT;
    '*[\n  _type == "shoppingCart"\n  && clerkUserId == $clerkUserId\n] | order(updatedAt desc)[0] {\n  _id,\n  updatedAt,\n  items[]{\n    _key,\n    quantity,\n    "productId": product._ref,\n    "productExists": defined(product->._id),\n    "name": coalesce(product->title, product->name, productName),\n    "price": coalesce(product->price, priceAtSave),\n    "image": coalesce(product->images[0].asset->url, imageUrl),\n    "slug": coalesce(product->slug.current, slug)\n  }\n}': CART_BY_USER_QUERY_RESULT;
    '*[\n  _type == "product"\n  && _id in $productIds\n] {\n  _id,\n  "name": coalesce(title, name),\n  price,\n  "image": images[0].asset->url,\n  "slug": slug.current\n}': CART_PRODUCTS_QUERY_RESULT;
    '*[\n  _type == "shoppingCart"\n  && clerkUserId == $clerkUserId\n] | order(updatedAt desc)[0] {\n  _id\n}': CART_DOCUMENT_BY_USER_QUERY_RESULT;
    '*[\n  _type == "category"\n] | order(coalesce(displayOrder, 2147483647) asc, title asc) {\n  _id,\n  title,\n  "slug": slug.current,\n  "parentId": parentCategory._ref,\n  displayOrder,\n  "image": image{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}': ALL_CATEGORIES_QUERY_RESULT;
    '*[\n  _type == "category"\n  && slug.current == $slug\n][0] {\n  _id,\n  title,\n  "slug": slug.current,\n  "parentId": parentCategory._ref,\n  displayOrder,\n  "image": image{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}': CATEGORY_BY_SLUG_QUERY_RESULT;
    '*[\n  _type == "customer"\n  && clerkUserId == $clerkUserId\n] | order(createdAt desc)[0] {\n  _id,\n  email,\n  name,\n  shippingAddress {\n    name,\n    line1,\n    line2,\n    city,\n    postcode,\n    county,\n    country\n  }\n}': CUSTOMER_ADDRESS_BY_USER_QUERY_RESULT;
    '*[\n  _type == "order"\n  && clerkUserId == $clerkUserId\n] | order(createdAt desc) {\n  _id,\n  orderNumber,\n  "total": coalesce(totalPrice, total),\n  status,\n  createdAt,\n  "itemCount": select(defined(products) => count(products), count(items)),\n  "itemNames": select(\n    defined(products) => products[]->{"value": coalesce(title, name)}.value,\n    coalesce(items[].product->title, items[].product->name)\n  ),\n  "itemImages": select(\n    defined(products) => products[]->images[0].asset->url,\n    items[].product->images[0].asset->url\n  )\n}': ORDERS_BY_USER_QUERY_RESULT;
    '*[\n  _type == "order"\n  && _id == $id\n][0] {\n  _id,\n  orderNumber,\n  clerkUserId,\n  "email": coalesce(customerEmail, email),\n  products[]->{\n    _id,\n    "name": coalesce(title, name),\n    "slug": slug.current,\n    "image": images[0]{\n      asset->{\n        _id,\n        url\n      }\n    }\n  },\n  quantities,\n  productPrices,\n  subtotal,\n  shippingFee,\n  "legacyItems": items[]{\n    _key,\n    quantity,\n    priceAtPurchase,\n    product->{\n      _id,\n      "name": coalesce(title, name),\n      "slug": slug.current,\n      "image": images[0]{\n        asset->{\n          _id,\n          url\n        }\n      }\n    }\n  },\n  "total": coalesce(totalPrice, total),\n  status,\n  "address": coalesce(shippingAddress, address),\n  paystackReference,\n  createdAt\n}': ORDER_BY_ID_QUERY_RESULT;
    '*[\n  _type == "order"\n] | order(createdAt desc) [0...$limit] {\n  _id,\n  orderNumber,\n  "email": coalesce(customerEmail, email),\n  "total": coalesce(totalPrice, total),\n  status,\n  createdAt\n}': RECENT_ORDERS_QUERY_RESULT;
    '*[\n  _type == "order"\n  && paystackReference == $paystackReference\n][0]{ _id }': ORDER_BY_PAYSTACK_REFERENCE_QUERY_RESULT;
    '*[\n  _type == "order"\n  && paystackReference == $paystackReference\n][0]{\n  _id,\n  clerkUserId,\n  status\n}': ORDER_STATUS_BY_PAYSTACK_REFERENCE_QUERY_RESULT;
    '*[\n  _type == "product"\n] | order(coalesce(title, name) asc) {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  description,\n  price,\n  "images": images[]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  dimensions,\n  stock,\n  featured,\n  assemblyRequired\n}': ALL_PRODUCTS_QUERY_RESULT;
    '*[\n  _type == "product"\n  && stock > 0\n  && featured == true\n] | order(coalesce(title, name) asc) [0...6] {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  description,\n  price,\n  "images": images[]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  brand->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  stock\n}': FEATURED_PRODUCTS_QUERY_RESULT;
    '*[\n  _type == "product"\n  && category->slug.current == $categorySlug\n] | order(coalesce(title, name) asc) {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  price,\n  "image": images[0]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  stock\n}': PRODUCTS_BY_CATEGORY_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (slug.current == $identifier || _id == $identifier)\n][0] {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  description,\n  features[]{_key, title, description},\n  price,\n  "images": images[]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  brand->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  color,\n  size,\n  dimensions,\n  stock,\n  featured,\n  assemblyRequired\n}': PRODUCT_BY_SLUG_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (\n    coalesce(title, name) match $searchQuery + "*"\n    || description match $searchQuery + "*"\n    || aiKeywords[] match $searchQuery + "*"\n    || aiTags[] match $searchQuery + "*"\n  )\n] | score(\n  boost(coalesce(title, name) match $searchQuery + "*", 3),\n  boost(aiKeywords[] match $searchQuery + "*", 2),\n  boost(aiTags[] match $searchQuery + "*", 2),\n  boost(description match $searchQuery + "*", 1)\n) | order(_score desc) {\n  _id,\n  _score,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  price,\n  "image": images[0]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  stock\n}': SEARCH_PRODUCTS_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (count($categoryIds) == 0 || category._ref in $categoryIds)\n  && (count($brandIds) == 0 || brand._ref in $brandIds)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n] | order(coalesce(title, name) asc) {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  price,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  brand->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  stock\n}': FILTER_PRODUCTS_BY_NAME_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (count($categoryIds) == 0 || category._ref in $categoryIds)\n  && (count($brandIds) == 0 || brand._ref in $brandIds)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n] | order(price asc) {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  price,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  brand->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  stock\n}': FILTER_PRODUCTS_BY_PRICE_ASC_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (count($categoryIds) == 0 || category._ref in $categoryIds)\n  && (count($brandIds) == 0 || brand._ref in $brandIds)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n] | order(price desc) {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  price,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  brand->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  stock\n}': FILTER_PRODUCTS_BY_PRICE_DESC_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (count($categoryIds) == 0 || category._ref in $categoryIds)\n  && (count($brandIds) == 0 || brand._ref in $brandIds)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n] | score(\n  boost(coalesce(title, name) match $searchQuery + "*", 3),\n  boost(aiKeywords[] match $searchQuery + "*", 2),\n  boost(aiTags[] match $searchQuery + "*", 2),\n  boost(features[].title match $searchQuery + "*", 2),\n  boost(features[].description match $searchQuery + "*", 1),\n  boost(description match $searchQuery + "*", 1)\n) | order(_score desc, coalesce(title, name) asc) {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  price,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  brand->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  stock\n}': FILTER_PRODUCTS_BY_RELEVANCE_QUERY_RESULT;
    '*[\n  \n  _type == "product"\n  && (count($categoryIds) == 0 || category._ref in $categoryIds)\n  && (count($brandIds) == 0 || brand._ref in $brandIds)\n  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n\n  && defined(price)\n].price': PRODUCT_PRICE_FACET_QUERY_RESULT;
    '*[\n  _type == "product"\n  && _id in $ids\n] {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  price,\n  "image": images[0]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  stock\n}': PRODUCTS_BY_IDS_QUERY_RESULT;
    '*[\n  _type == "product"\n  && stock > 0\n  && stock <= 5\n] | order(stock asc) {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  stock,\n  "image": images[0]{\n    asset->{\n      _id,\n      url\n    }\n  }\n}': LOW_STOCK_PRODUCTS_QUERY_RESULT;
    '*[\n  _type == "product"\n  && stock == 0\n] | order(coalesce(title, name) asc) {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  "image": images[0]{\n    asset->{\n      _id,\n      url\n    }\n  }\n}': OUT_OF_STOCK_PRODUCTS_QUERY_RESULT;
    '*[\n  \n  _type == "product"\n  && (count($categoryIds) == 0 || category._ref in $categoryIds)\n  && (count($brandIds) == 0 || brand._ref in $brandIds)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n\n] | score(\n  boost(coalesce(title, name) match $searchQuery + "*", 3),\n  boost(aiKeywords[] match $searchQuery + "*", 2),\n  boost(aiTags[] match $searchQuery + "*", 2),\n  boost(features[].title match $searchQuery + "*", 2),\n  boost(features[].description match $searchQuery + "*", 1),\n  boost(description match $searchQuery + "*", 1)\n) | order(_score desc, coalesce(title, name) asc) [0...20] {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  description,\n  features[]{_key, title, description},\n  price,\n  "image": images[0]{\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  brand->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  color,\n  size,\n  dimensions,\n  stock,\n  featured,\n  assemblyRequired\n}': AI_SEARCH_PRODUCTS_QUERY_RESULT;
    '*[\n  _type == "promotion"\n  && status == "active"\n  && (!defined(startsAt) || dateTime(startsAt) <= dateTime(now()))\n  && (!defined(endsAt) || dateTime(endsAt) >= dateTime(now()))\n] | order(sortOrder asc, _createdAt desc) [0...6] {\n  _id,\n  internalTitle,\n  mediaType,\n  image {\n    asset->{\n      _id,\n      url,\n      metadata {\n        lqip,\n        dimensions { width, height }\n      }\n    },\n    alt,\n    hotspot,\n    crop\n  },\n  youtubeUrl,\n  muxVideo {\n    asset->{\n      playbackId,\n      status,\n      filename,\n      data {\n        aspect_ratio,\n        duration\n      }\n    }\n  },\n  destinationUrl\n}': ACTIVE_PROMOTIONS_QUERY_RESULT;
    '*[\n  _type == "product" && _id == $productId\n][0] {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  stock\n}': RESTOCK_PRODUCT_QUERY_RESULT;
    '*[\n  _type == "restockSubscription"\n  && clerkUserId == $clerkUserId\n  && product._ref == $productId\n  && status == "pending"\n] | order(requestedAt desc)[0] {\n  _id,\n  status,\n  requestedAt\n}': ACTIVE_RESTOCK_SUBSCRIPTION_QUERY_RESULT;
    '*[\n  _type == "order"\n  && clerkUserId == $clerkUserId\n  && status == "delivered"\n] | order(createdAt desc) {\n  _id,\n  orderNumber,\n  createdAt,\n  deliveredAt,\n  "deliveryDate": coalesce(deliveredAt, _updatedAt, createdAt),\n  products[]->{\n    _id,\n    "name": coalesce(title, name),\n    "returnEligibility": coalesce(returnEligibility, "standard"),\n    "returnWindowDays": coalesce(returnWindowDays, 14),\n    returnPolicyNote\n  },\n  quantities,\n  productPrices,\n  "legacyItems": items[]{\n    _key,\n    quantity,\n    priceAtPurchase,\n    product->{\n      _id,\n      "name": coalesce(title, name),\n      "returnEligibility": coalesce(returnEligibility, "standard"),\n      "returnWindowDays": coalesce(returnWindowDays, 14),\n      returnPolicyNote\n    }\n  }\n}': DELIVERED_ORDERS_FOR_RETURNS_QUERY_RESULT;
    '*[\n  _type == "order"\n  && _id == $orderId\n][0] {\n  _id,\n  orderNumber,\n  clerkUserId,\n  "email": coalesce(customerEmail, email),\n  status,\n  deliveredAt,\n  createdAt,\n  "deliveryDate": coalesce(deliveredAt, _updatedAt, createdAt),\n  products[]->{\n    _id,\n    "name": coalesce(title, name),\n    "returnEligibility": coalesce(returnEligibility, "standard"),\n    "returnWindowDays": coalesce(returnWindowDays, 14),\n    returnPolicyNote\n  },\n  quantities,\n  productPrices,\n  "legacyItems": items[]{\n    _key,\n    quantity,\n    priceAtPurchase,\n    product->{\n      _id,\n      "name": coalesce(title, name),\n      "returnEligibility": coalesce(returnEligibility, "standard"),\n      "returnWindowDays": coalesce(returnWindowDays, 14),\n      returnPolicyNote\n    }\n  }\n}': RETURN_ORDER_BY_ID_QUERY_RESULT;
    '*[\n  _type == "returnRequest"\n  && order._ref == $orderId\n  && status in ["pending", "approved", "received", "completed"]\n] {\n  items[]{\n    quantity,\n    "productId": product._ref\n  }\n}': ACTIVE_RETURN_ITEMS_BY_ORDER_QUERY_RESULT;
    '*[\n  _type == "returnRequest"\n  && clerkUserId == $clerkUserId\n] | order(requestedAt desc) {\n  _id,\n  requestNumber,\n  "orderId": order._ref,\n  "orderNumber": order->orderNumber,\n  resolution,\n  reason,\n  notes,\n  status,\n  adminNotes,\n  requestedAt,\n  reviewedAt,\n  completedAt,\n  "evidenceImageUrls": evidenceImages[].asset->url,\n  items[]{\n    _key,\n    quantity,\n    productName,\n    priceAtPurchase,\n    "productId": product._ref\n  }\n}': RETURNS_BY_USER_QUERY_RESULT;
    '*[\n  _type == "shippingSettings" && _id == "shippingSettings"\n][0] {\n  mombasaFee,\n  coastalFee,\n  nairobiFee,\n  otherKenyaFee\n}': SHIPPING_SETTINGS_QUERY_RESULT;
    '*[\n  _type == "order"\n  && createdAt >= $startDate\n  && !(_id in path("drafts.**"))\n] | order(createdAt desc) {\n  _id,\n  orderNumber,\n  "total": coalesce(totalPrice, total),\n  status,\n  createdAt,\n  "itemCount": select(defined(products) => count(products), count(items)),\n  products[]->{\n    "productName": coalesce(title, name),\n    "productId": _id,\n    price\n  },\n  quantities,\n  productPrices,\n  "legacyItems": items[]{\n    quantity,\n    priceAtPurchase,\n    "productName": coalesce(product->title, product->name),\n    "productId": product->_id\n  }\n}': ORDERS_LAST_7_DAYS_QUERY_RESULT;
    '{\n  "paid": count(*[_type == "order" && status == "paid" && !(_id in path("drafts.**"))]),\n  "shipped": count(*[_type == "order" && status == "shipped" && !(_id in path("drafts.**"))]),\n  "delivered": count(*[_type == "order" && status == "delivered" && !(_id in path("drafts.**"))]),\n  "cancelled": count(*[_type == "order" && status == "cancelled" && !(_id in path("drafts.**"))])\n}': ORDER_STATUS_DISTRIBUTION_QUERY_RESULT;
    '*[\n  _type == "order"\n  && status in ["paid", "shipped", "delivered"]\n  && !(_id in path("drafts.**"))\n] {\n  products[]->{\n    "productId": _id,\n    "productName": coalesce(title, name),\n    "productPrice": price\n  },\n  quantities,\n  productPrices,\n  "legacyItems": items[]{\n    "productId": product->_id,\n    "productName": coalesce(product->title, product->name),\n    "productPrice": product->price,\n    quantity\n  }\n}': TOP_SELLING_PRODUCTS_QUERY_RESULT;
    '*[_type == "product"] {\n  _id,\n  "name": coalesce(title, name),\n  price,\n  stock,\n  "category": category->title\n}': PRODUCTS_INVENTORY_QUERY_RESULT;
    '*[\n  _type == "order"\n  && status == "paid"\n  && !(_id in path("drafts.**"))\n] | order(createdAt asc) {\n  _id,\n  orderNumber,\n  "total": coalesce(totalPrice, total),\n  createdAt,\n  "email": coalesce(customerEmail, email),\n  "itemCount": select(defined(products) => count(products), count(items))\n}': UNFULFILLED_ORDERS_QUERY_RESULT;
    '{\n  "currentPeriod": math::sum(*[\n    _type == "order"\n    && status in ["paid", "shipped", "delivered"]\n    && createdAt >= $currentStart\n    && !(_id in path("drafts.**"))\n  ]{"value": coalesce(totalPrice, total)}.value),\n  "previousPeriod": math::sum(*[\n    _type == "order"\n    && status in ["paid", "shipped", "delivered"]\n    && createdAt >= $previousStart\n    && createdAt < $currentStart\n    && !(_id in path("drafts.**"))\n  ]{"value": coalesce(totalPrice, total)}.value),\n  "currentOrderCount": count(*[\n    _type == "order"\n    && createdAt >= $currentStart\n    && !(_id in path("drafts.**"))\n  ]),\n  "previousOrderCount": count(*[\n    _type == "order"\n    && createdAt >= $previousStart\n    && createdAt < $currentStart\n    && !(_id in path("drafts.**"))\n  ])\n}': REVENUE_BY_PERIOD_QUERY_RESULT;
    '*[\n  _type == "product" && _id == $productId\n][0] {\n  _id,\n  "name": coalesce(title, name)\n}': WISHLIST_PRODUCT_QUERY_RESULT;
    '*[\n  _type == "wishlistItem"\n  && clerkUserId == $clerkUserId\n  && product._ref == $productId\n] | order(createdAt desc)[0] {\n  _id,\n  createdAt\n}': WISHLIST_ITEM_QUERY_RESULT;
    'count(*[\n  _type == "wishlistItem"\n  && clerkUserId == $clerkUserId\n  && defined(product->._id)\n])': WISHLIST_COUNT_QUERY_RESULT;
    '*[\n  _type == "wishlistItem"\n  && clerkUserId == $clerkUserId\n  && defined(product->._id)\n] | order(createdAt desc) {\n  _id,\n  createdAt,\n  product->{\n    _id,\n    "name": coalesce(title, name),\n    "slug": slug.current,\n    price,\n    "images": images[0...4]{\n      _key,\n      asset->{\n        _id,\n        url\n      }\n    },\n    category->{\n      _id,\n      title,\n      "slug": slug.current\n    },\n    brand->{\n      _id,\n      title,\n      "slug": slug.current\n    },\n    stock\n  }\n}': WISHLIST_BY_USER_QUERY_RESULT;
  }
}
