/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type CustomerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "customer";
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  items?: Array<{
    product?: ProductReference;
    quantity?: number;
    priceAtPurchase?: number;
    _key: string;
  }>;
  total?: number;
  totalPrice?: number;
  products?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  quantities?: Array<number>;
  productPrices?: Array<number>;
  status?: "paid" | "shipped" | "delivered" | "cancelled";
  customer?: CustomerReference;
  clerkUserId?: string;
  email?: string;
  customerEmail?: string;
  address?: {
    name?: string;
    line1?: string;
    line2?: string;
    city?: string;
    postcode?: string;
    country?: string;
  };
  shippingAddress?: {
    name?: string;
    line1?: string;
    line2?: string;
    city?: string;
    postcode?: string;
    country?: string;
  };
  paystackPaymentId?: string;
  paystackReference?: string;
  inventoryAdjusted?: boolean;
  inventoryIssue?: string;
  createdAt?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type BrandReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "brand";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  title?: string;
  slug?: Slug;
  description?: string;
  features?: Array<{
    title?: string;
    description?: string;
    _type: "productFeature";
    _key: string;
  }>;
  price?: number;
  category?: CategoryReference;
  brand?: BrandReference;
  size?: string;
  material?: string;
  color?: string;
  aiKeywords?: Array<string>;
  aiTags?: Array<string>;
  dimensions?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  stock?: number;
  featured?: boolean;
  assemblyRequired?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Customer = {
  _id: string;
  _type: "customer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  name?: string;
  clerkUserId?: string;
  paystackCustomerId?: string;
  createdAt?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  icon?: string;
  parentCategory?: CategoryReference;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProductReference
  | CustomerReference
  | Order
  | CategoryReference
  | BrandReference
  | SanityImageAssetReference
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Customer
  | Category
  | Brand
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/sanity/queries/brands.ts
// Variable: ALL_BRANDS_QUERY
// Query: *[  _type == "brand"] | order(title asc) {  _id,  title,  "slug": slug.current,  logo{    asset->{      _id,      url    }  }}
export type ALL_BRANDS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  logo: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;

// Source: lib/sanity/queries/brands.ts
// Variable: BRANDS_BY_SLUGS_QUERY
// Query: *[  _type == "brand"  && slug.current in $slugs] {  _id,  title,  "slug": slug.current}
export type BRANDS_BY_SLUGS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
}>;

// Source: lib/sanity/queries/categories.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[  _type == "category"] | order(title asc) {  _id,  title,  "slug": slug.current,  "parentId": parentCategory._ref,  "image": image{    asset->{      _id,      url    },    hotspot  }}
export type ALL_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  parentId: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
}>;

// Source: lib/sanity/queries/categories.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[  _type == "category"  && slug.current == $slug][0] {  _id,  title,  "slug": slug.current,  "parentId": parentCategory._ref,  "image": image{    asset->{      _id,      url    },    hotspot  }}
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  parentId: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
} | null;

// Source: lib/sanity/queries/orders.ts
// Variable: ORDERS_BY_USER_QUERY
// Query: *[  _type == "order"  && clerkUserId == $clerkUserId] | order(createdAt desc) {  _id,  orderNumber,  "total": coalesce(totalPrice, total),  status,  createdAt,  "itemCount": select(defined(products) => count(products), count(items)),  "itemNames": select(    defined(products) => products[]->{"value": coalesce(title, name)}.value,    coalesce(items[].product->title, items[].product->name)  ),  "itemImages": select(    defined(products) => products[]->images[0].asset->url,    items[].product->images[0].asset->url  )}
export type ORDERS_BY_USER_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: string | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  createdAt: string | null;
  itemCount: number | null;
  itemNames: Array<string | null> | null;
  itemImages: Array<string | null> | null;
}>;

// Source: lib/sanity/queries/orders.ts
// Variable: ORDER_BY_ID_QUERY
// Query: *[  _type == "order"  && _id == $id][0] {  _id,  orderNumber,  clerkUserId,  "email": coalesce(customerEmail, email),  products[]->{    _id,    "name": coalesce(title, name),    "slug": slug.current,    "image": images[0]{      asset->{        _id,        url      }    }  },  quantities,  productPrices,  "legacyItems": items[]{    _key,    quantity,    priceAtPurchase,    product->{      _id,      "name": coalesce(title, name),      "slug": slug.current,      "image": images[0]{        asset->{          _id,          url        }      }    }  },  "total": coalesce(totalPrice, total),  status,  "address": coalesce(shippingAddress, address),  paystackReference,  createdAt}
export type ORDER_BY_ID_QUERY_RESULT = {
  _id: string;
  orderNumber: string | null;
  clerkUserId: string | null;
  email: string | null;
  products: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    image: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
    } | null;
  }> | null;
  quantities: Array<number> | null;
  productPrices: Array<number> | null;
  legacyItems: Array<{
    _key: string;
    quantity: number | null;
    priceAtPurchase: number | null;
    product: {
      _id: string;
      name: string | null;
      slug: string | null;
      image: {
        asset: {
          _id: string;
          url: string | null;
        } | null;
      } | null;
    } | null;
  }> | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  address: {
    name?: string;
    line1?: string;
    line2?: string;
    city?: string;
    postcode?: string;
    country?: string;
  } | null;
  paystackReference: string | null;
  createdAt: string | null;
} | null;

// Source: lib/sanity/queries/orders.ts
// Variable: ORDER_BY_PAYSTACK_REFERENCE_QUERY
// Query: *[  _type == "order"  && paystackReference == $paystackReference][0]{ _id }
export type ORDER_BY_PAYSTACK_REFERENCE_QUERY_RESULT = {
  _id: string;
} | null;

// Source: lib/sanity/queries/orders.ts
// Variable: ORDER_STATUS_BY_PAYSTACK_REFERENCE_QUERY
// Query: *[  _type == "order"  && paystackReference == $paystackReference][0]{  _id,  clerkUserId,  status}
export type ORDER_STATUS_BY_PAYSTACK_REFERENCE_QUERY_RESULT = {
  _id: string;
  clerkUserId: string | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
} | null;

// Source: lib/sanity/queries/products.ts
// Variable: FEATURED_PRODUCTS_QUERY
// Query: *[  _type == "product"  && stock > 0  && featured == true] | order(coalesce(title, name) asc) [0...6] {  _id,  "name": coalesce(title, name),  "slug": slug.current,  description,  price,  "images": images[]{    _key,    asset->{      _id,      url    },    hotspot  },  category->{    _id,    title,    "slug": slug.current  },  brand->{    _id,    title,    "slug": slug.current  },  stock}
export type FEATURED_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  brand: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[  _type == "product"  && (slug.current == $identifier || _id == $identifier)][0] {  _id,  "name": coalesce(title, name),  "slug": slug.current,  description,  features[]{_key, title, description},  price,  "images": images[]{    _key,    asset->{      _id,      url    },    hotspot  },  category->{    _id,    title,    "slug": slug.current  },  brand->{    _id,    title,    "slug": slug.current  },  color,  size,  dimensions,  stock,  featured,  assemblyRequired}
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  features: Array<{
    _key: string;
    title: string | null;
    description: string | null;
  }> | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  brand: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  color: string | null;
  size: string | null;
  dimensions: string | null;
  stock: number | null;
  featured: boolean | null;
  assemblyRequired: boolean | null;
} | null;

// Source: lib/sanity/queries/products.ts
// Variable: FILTER_PRODUCTS_BY_NAME_QUERY
// Query: *[  _type == "product"  && (count($categoryIds) == 0 || category._ref in $categoryIds)  && (count($brandIds) == 0 || brand._ref in $brandIds)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")  && ($inStock == false || stock > 0)] | order(coalesce(title, name) asc) {  _id,  "name": coalesce(title, name),  "slug": slug.current,  price,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  brand->{    _id,    title,    "slug": slug.current  },  stock}
export type FILTER_PRODUCTS_BY_NAME_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  brand: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: FILTER_PRODUCTS_BY_PRICE_ASC_QUERY
// Query: *[  _type == "product"  && (count($categoryIds) == 0 || category._ref in $categoryIds)  && (count($brandIds) == 0 || brand._ref in $brandIds)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")  && ($inStock == false || stock > 0)] | order(price asc) {  _id,  "name": coalesce(title, name),  "slug": slug.current,  price,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  brand->{    _id,    title,    "slug": slug.current  },  stock}
export type FILTER_PRODUCTS_BY_PRICE_ASC_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  brand: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: FILTER_PRODUCTS_BY_PRICE_DESC_QUERY
// Query: *[  _type == "product"  && (count($categoryIds) == 0 || category._ref in $categoryIds)  && (count($brandIds) == 0 || brand._ref in $brandIds)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")  && ($inStock == false || stock > 0)] | order(price desc) {  _id,  "name": coalesce(title, name),  "slug": slug.current,  price,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  brand->{    _id,    title,    "slug": slug.current  },  stock}
export type FILTER_PRODUCTS_BY_PRICE_DESC_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  brand: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: FILTER_PRODUCTS_BY_RELEVANCE_QUERY
// Query: *[  _type == "product"  && (count($categoryIds) == 0 || category._ref in $categoryIds)  && (count($brandIds) == 0 || brand._ref in $brandIds)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")  && ($inStock == false || stock > 0)] | score(  boost(coalesce(title, name) match $searchQuery + "*", 3),  boost(aiKeywords[] match $searchQuery + "*", 2),  boost(aiTags[] match $searchQuery + "*", 2),  boost(features[].title match $searchQuery + "*", 2),  boost(features[].description match $searchQuery + "*", 1),  boost(description match $searchQuery + "*", 1)) | order(_score desc, coalesce(title, name) asc) {  _id,  "name": coalesce(title, name),  "slug": slug.current,  price,  "images": images[0...4]{    _key,    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  brand->{    _id,    title,    "slug": slug.current  },  stock}
export type FILTER_PRODUCTS_BY_RELEVANCE_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  brand: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: PRODUCT_PRICE_FACET_QUERY
// Query: *[    _type == "product"  && (count($categoryIds) == 0 || category._ref in $categoryIds)  && (count($brandIds) == 0 || brand._ref in $brandIds)  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")  && ($inStock == false || stock > 0)  && defined(price)].price
export type PRODUCT_PRICE_FACET_QUERY_RESULT = Array<number | null>;

// Source: lib/sanity/queries/products.ts
// Variable: PRODUCTS_BY_IDS_QUERY
// Query: *[  _type == "product"  && _id in $ids] {  _id,  "name": coalesce(title, name),  "slug": slug.current,  price,  "image": images[0]{    asset->{      _id,      url    },    hotspot  },  stock}
export type PRODUCTS_BY_IDS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  stock: number | null;
}>;

// Source: lib/sanity/queries/products.ts
// Variable: AI_SEARCH_PRODUCTS_QUERY
// Query: *[    _type == "product"  && (count($categoryIds) == 0 || category._ref in $categoryIds)  && (count($brandIds) == 0 || brand._ref in $brandIds)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")  && ($inStock == false || stock > 0)] | score(  boost(coalesce(title, name) match $searchQuery + "*", 3),  boost(aiKeywords[] match $searchQuery + "*", 2),  boost(aiTags[] match $searchQuery + "*", 2),  boost(features[].title match $searchQuery + "*", 2),  boost(features[].description match $searchQuery + "*", 1),  boost(description match $searchQuery + "*", 1)) | order(_score desc, coalesce(title, name) asc) [0...20] {  _id,  "name": coalesce(title, name),  "slug": slug.current,  description,  features[]{_key, title, description},  price,  "image": images[0]{    asset->{      _id,      url    }  },  category->{    _id,    title,    "slug": slug.current  },  brand->{    _id,    title,    "slug": slug.current  },  color,  size,  dimensions,  stock,  featured,  assemblyRequired}
export type AI_SEARCH_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  features: Array<{
    _key: string;
    title: string | null;
    description: string | null;
  }> | null;
  price: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  brand: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  color: string | null;
  size: string | null;
  dimensions: string | null;
  stock: number | null;
  featured: boolean | null;
  assemblyRequired: boolean | null;
}>;

// Source: lib/sanity/queries/stats.ts
// Variable: ORDERS_LAST_7_DAYS_QUERY
// Query: *[  _type == "order"  && createdAt >= $startDate  && !(_id in path("drafts.**"))] | order(createdAt desc) {  _id,  orderNumber,  "total": coalesce(totalPrice, total),  status,  createdAt,  "itemCount": select(defined(products) => count(products), count(items)),  products[]->{    "productName": coalesce(title, name),    "productId": _id,    price  },  quantities,  productPrices,  "legacyItems": items[]{    quantity,    priceAtPurchase,    "productName": coalesce(product->title, product->name),    "productId": product->_id  }}
export type ORDERS_LAST_7_DAYS_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: string | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  createdAt: string | null;
  itemCount: number | null;
  products: Array<{
    productName: string | null;
    productId: string;
    price: number | null;
  }> | null;
  quantities: Array<number> | null;
  productPrices: Array<number> | null;
  legacyItems: Array<{
    quantity: number | null;
    priceAtPurchase: number | null;
    productName: string | null;
    productId: string | null;
  }> | null;
}>;

// Source: lib/sanity/queries/stats.ts
// Variable: ORDER_STATUS_DISTRIBUTION_QUERY
// Query: {  "paid": count(*[_type == "order" && status == "paid" && !(_id in path("drafts.**"))]),  "shipped": count(*[_type == "order" && status == "shipped" && !(_id in path("drafts.**"))]),  "delivered": count(*[_type == "order" && status == "delivered" && !(_id in path("drafts.**"))]),  "cancelled": count(*[_type == "order" && status == "cancelled" && !(_id in path("drafts.**"))])}
export type ORDER_STATUS_DISTRIBUTION_QUERY_RESULT = {
  paid: number;
  shipped: number;
  delivered: number;
  cancelled: number;
};

// Source: lib/sanity/queries/stats.ts
// Variable: TOP_SELLING_PRODUCTS_QUERY
// Query: *[  _type == "order"  && status in ["paid", "shipped", "delivered"]  && !(_id in path("drafts.**"))] {  products[]->{    "productId": _id,    "productName": coalesce(title, name),    "productPrice": price  },  quantities,  productPrices,  "legacyItems": items[]{    "productId": product->_id,    "productName": coalesce(product->title, product->name),    "productPrice": product->price,    quantity  }}
export type TOP_SELLING_PRODUCTS_QUERY_RESULT = Array<{
  products: Array<{
    productId: string;
    productName: string | null;
    productPrice: number | null;
  }> | null;
  quantities: Array<number> | null;
  productPrices: Array<number> | null;
  legacyItems: Array<{
    productId: string | null;
    productName: string | null;
    productPrice: number | null;
    quantity: number | null;
  }> | null;
}>;

// Source: lib/sanity/queries/stats.ts
// Variable: PRODUCTS_INVENTORY_QUERY
// Query: *[_type == "product"] {  _id,  "name": coalesce(title, name),  price,  stock,  "category": category->title}
export type PRODUCTS_INVENTORY_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  price: number | null;
  stock: number | null;
  category: string | null;
}>;

// Source: lib/sanity/queries/stats.ts
// Variable: UNFULFILLED_ORDERS_QUERY
// Query: *[  _type == "order"  && status == "paid"  && !(_id in path("drafts.**"))] | order(createdAt asc) {  _id,  orderNumber,  "total": coalesce(totalPrice, total),  createdAt,  "email": coalesce(customerEmail, email),  "itemCount": select(defined(products) => count(products), count(items))}
export type UNFULFILLED_ORDERS_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: string | null;
  total: number | null;
  createdAt: string | null;
  email: string | null;
  itemCount: number | null;
}>;

// Source: lib/sanity/queries/stats.ts
// Variable: REVENUE_BY_PERIOD_QUERY
// Query: {  "currentPeriod": math::sum(*[    _type == "order"    && status in ["paid", "shipped", "delivered"]    && createdAt >= $currentStart    && !(_id in path("drafts.**"))  ]{"value": coalesce(totalPrice, total)}.value),  "previousPeriod": math::sum(*[    _type == "order"    && status in ["paid", "shipped", "delivered"]    && createdAt >= $previousStart    && createdAt < $currentStart    && !(_id in path("drafts.**"))  ]{"value": coalesce(totalPrice, total)}.value),  "currentOrderCount": count(*[    _type == "order"    && createdAt >= $currentStart    && !(_id in path("drafts.**"))  ]),  "previousOrderCount": count(*[    _type == "order"    && createdAt >= $previousStart    && createdAt < $currentStart    && !(_id in path("drafts.**"))  ])}
export type REVENUE_BY_PERIOD_QUERY_RESULT = {
  currentPeriod: number;
  previousPeriod: number;
  currentOrderCount: number;
  previousOrderCount: number;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[\n  _type == "brand"\n] | order(title asc) {\n  _id,\n  title,\n  "slug": slug.current,\n  logo{\n    asset->{\n      _id,\n      url\n    }\n  }\n}': ALL_BRANDS_QUERY_RESULT;
    '*[\n  _type == "brand"\n  && slug.current in $slugs\n] {\n  _id,\n  title,\n  "slug": slug.current\n}': BRANDS_BY_SLUGS_QUERY_RESULT;
    '*[\n  _type == "category"\n] | order(title asc) {\n  _id,\n  title,\n  "slug": slug.current,\n  "parentId": parentCategory._ref,\n  "image": image{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}': ALL_CATEGORIES_QUERY_RESULT;
    '*[\n  _type == "category"\n  && slug.current == $slug\n][0] {\n  _id,\n  title,\n  "slug": slug.current,\n  "parentId": parentCategory._ref,\n  "image": image{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}': CATEGORY_BY_SLUG_QUERY_RESULT;
    '*[\n  _type == "order"\n  && clerkUserId == $clerkUserId\n] | order(createdAt desc) {\n  _id,\n  orderNumber,\n  "total": coalesce(totalPrice, total),\n  status,\n  createdAt,\n  "itemCount": select(defined(products) => count(products), count(items)),\n  "itemNames": select(\n    defined(products) => products[]->{"value": coalesce(title, name)}.value,\n    coalesce(items[].product->title, items[].product->name)\n  ),\n  "itemImages": select(\n    defined(products) => products[]->images[0].asset->url,\n    items[].product->images[0].asset->url\n  )\n}': ORDERS_BY_USER_QUERY_RESULT;
    '*[\n  _type == "order"\n  && _id == $id\n][0] {\n  _id,\n  orderNumber,\n  clerkUserId,\n  "email": coalesce(customerEmail, email),\n  products[]->{\n    _id,\n    "name": coalesce(title, name),\n    "slug": slug.current,\n    "image": images[0]{\n      asset->{\n        _id,\n        url\n      }\n    }\n  },\n  quantities,\n  productPrices,\n  "legacyItems": items[]{\n    _key,\n    quantity,\n    priceAtPurchase,\n    product->{\n      _id,\n      "name": coalesce(title, name),\n      "slug": slug.current,\n      "image": images[0]{\n        asset->{\n          _id,\n          url\n        }\n      }\n    }\n  },\n  "total": coalesce(totalPrice, total),\n  status,\n  "address": coalesce(shippingAddress, address),\n  paystackReference,\n  createdAt\n}': ORDER_BY_ID_QUERY_RESULT;
    '*[\n  _type == "order"\n  && paystackReference == $paystackReference\n][0]{ _id }': ORDER_BY_PAYSTACK_REFERENCE_QUERY_RESULT;
    '*[\n  _type == "order"\n  && paystackReference == $paystackReference\n][0]{\n  _id,\n  clerkUserId,\n  status\n}': ORDER_STATUS_BY_PAYSTACK_REFERENCE_QUERY_RESULT;
    '*[\n  _type == "product"\n  && stock > 0\n  && featured == true\n] | order(coalesce(title, name) asc) [0...6] {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  description,\n  price,\n  "images": images[]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  brand->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  stock\n}': FEATURED_PRODUCTS_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (slug.current == $identifier || _id == $identifier)\n][0] {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  description,\n  features[]{_key, title, description},\n  price,\n  "images": images[]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  brand->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  color,\n  size,\n  dimensions,\n  stock,\n  featured,\n  assemblyRequired\n}': PRODUCT_BY_SLUG_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (count($categoryIds) == 0 || category._ref in $categoryIds)\n  && (count($brandIds) == 0 || brand._ref in $brandIds)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n] | order(coalesce(title, name) asc) {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  price,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  brand->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  stock\n}': FILTER_PRODUCTS_BY_NAME_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (count($categoryIds) == 0 || category._ref in $categoryIds)\n  && (count($brandIds) == 0 || brand._ref in $brandIds)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n] | order(price asc) {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  price,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  brand->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  stock\n}': FILTER_PRODUCTS_BY_PRICE_ASC_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (count($categoryIds) == 0 || category._ref in $categoryIds)\n  && (count($brandIds) == 0 || brand._ref in $brandIds)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n] | order(price desc) {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  price,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  brand->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  stock\n}': FILTER_PRODUCTS_BY_PRICE_DESC_QUERY_RESULT;
    '*[\n  _type == "product"\n  && (count($categoryIds) == 0 || category._ref in $categoryIds)\n  && (count($brandIds) == 0 || brand._ref in $brandIds)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n] | score(\n  boost(coalesce(title, name) match $searchQuery + "*", 3),\n  boost(aiKeywords[] match $searchQuery + "*", 2),\n  boost(aiTags[] match $searchQuery + "*", 2),\n  boost(features[].title match $searchQuery + "*", 2),\n  boost(features[].description match $searchQuery + "*", 1),\n  boost(description match $searchQuery + "*", 1)\n) | order(_score desc, coalesce(title, name) asc) {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  price,\n  "images": images[0...4]{\n    _key,\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  brand->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  stock\n}': FILTER_PRODUCTS_BY_RELEVANCE_QUERY_RESULT;
    '*[\n  \n  _type == "product"\n  && (count($categoryIds) == 0 || category._ref in $categoryIds)\n  && (count($brandIds) == 0 || brand._ref in $brandIds)\n  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n\n  && defined(price)\n].price': PRODUCT_PRICE_FACET_QUERY_RESULT;
    '*[\n  _type == "product"\n  && _id in $ids\n] {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  price,\n  "image": images[0]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  stock\n}': PRODUCTS_BY_IDS_QUERY_RESULT;
    '*[\n  \n  _type == "product"\n  && (count($categoryIds) == 0 || category._ref in $categoryIds)\n  && (count($brandIds) == 0 || brand._ref in $brandIds)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n  && ($searchQuery == "" || coalesce(title, name) match $searchQuery + "*" || description match $searchQuery + "*" || features[].title match $searchQuery + "*" || features[].description match $searchQuery + "*" || aiKeywords[] match $searchQuery + "*" || aiTags[] match $searchQuery + "*")\n  && ($inStock == false || stock > 0)\n\n] | score(\n  boost(coalesce(title, name) match $searchQuery + "*", 3),\n  boost(aiKeywords[] match $searchQuery + "*", 2),\n  boost(aiTags[] match $searchQuery + "*", 2),\n  boost(features[].title match $searchQuery + "*", 2),\n  boost(features[].description match $searchQuery + "*", 1),\n  boost(description match $searchQuery + "*", 1)\n) | order(_score desc, coalesce(title, name) asc) [0...20] {\n  _id,\n  "name": coalesce(title, name),\n  "slug": slug.current,\n  description,\n  features[]{_key, title, description},\n  price,\n  "image": images[0]{\n    asset->{\n      _id,\n      url\n    }\n  },\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  brand->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n  color,\n  size,\n  dimensions,\n  stock,\n  featured,\n  assemblyRequired\n}': AI_SEARCH_PRODUCTS_QUERY_RESULT;
    '*[\n  _type == "order"\n  && createdAt >= $startDate\n  && !(_id in path("drafts.**"))\n] | order(createdAt desc) {\n  _id,\n  orderNumber,\n  "total": coalesce(totalPrice, total),\n  status,\n  createdAt,\n  "itemCount": select(defined(products) => count(products), count(items)),\n  products[]->{\n    "productName": coalesce(title, name),\n    "productId": _id,\n    price\n  },\n  quantities,\n  productPrices,\n  "legacyItems": items[]{\n    quantity,\n    priceAtPurchase,\n    "productName": coalesce(product->title, product->name),\n    "productId": product->_id\n  }\n}': ORDERS_LAST_7_DAYS_QUERY_RESULT;
    '{\n  "paid": count(*[_type == "order" && status == "paid" && !(_id in path("drafts.**"))]),\n  "shipped": count(*[_type == "order" && status == "shipped" && !(_id in path("drafts.**"))]),\n  "delivered": count(*[_type == "order" && status == "delivered" && !(_id in path("drafts.**"))]),\n  "cancelled": count(*[_type == "order" && status == "cancelled" && !(_id in path("drafts.**"))])\n}': ORDER_STATUS_DISTRIBUTION_QUERY_RESULT;
    '*[\n  _type == "order"\n  && status in ["paid", "shipped", "delivered"]\n  && !(_id in path("drafts.**"))\n] {\n  products[]->{\n    "productId": _id,\n    "productName": coalesce(title, name),\n    "productPrice": price\n  },\n  quantities,\n  productPrices,\n  "legacyItems": items[]{\n    "productId": product->_id,\n    "productName": coalesce(product->title, product->name),\n    "productPrice": product->price,\n    quantity\n  }\n}': TOP_SELLING_PRODUCTS_QUERY_RESULT;
    '*[_type == "product"] {\n  _id,\n  "name": coalesce(title, name),\n  price,\n  stock,\n  "category": category->title\n}': PRODUCTS_INVENTORY_QUERY_RESULT;
    '*[\n  _type == "order"\n  && status == "paid"\n  && !(_id in path("drafts.**"))\n] | order(createdAt asc) {\n  _id,\n  orderNumber,\n  "total": coalesce(totalPrice, total),\n  createdAt,\n  "email": coalesce(customerEmail, email),\n  "itemCount": select(defined(products) => count(products), count(items))\n}': UNFULFILLED_ORDERS_QUERY_RESULT;
    '{\n  "currentPeriod": math::sum(*[\n    _type == "order"\n    && status in ["paid", "shipped", "delivered"]\n    && createdAt >= $currentStart\n    && !(_id in path("drafts.**"))\n  ]{"value": coalesce(totalPrice, total)}.value),\n  "previousPeriod": math::sum(*[\n    _type == "order"\n    && status in ["paid", "shipped", "delivered"]\n    && createdAt >= $previousStart\n    && createdAt < $currentStart\n    && !(_id in path("drafts.**"))\n  ]{"value": coalesce(totalPrice, total)}.value),\n  "currentOrderCount": count(*[\n    _type == "order"\n    && createdAt >= $currentStart\n    && !(_id in path("drafts.**"))\n  ]),\n  "previousOrderCount": count(*[\n    _type == "order"\n    && createdAt >= $previousStart\n    && createdAt < $currentStart\n    && !(_id in path("drafts.**"))\n  ])\n}': REVENUE_BY_PERIOD_QUERY_RESULT;
  }
}
